
---
# tasks file for nginx
- name: "Install gentoolkit"
  become: "yes"
  register: "install_gentoolkit_result"
  changed_when: >
    not install_gentoolkit_result.stdout |
    regex_search('gentoolkit already installed')
  shell: |
    if hash euse > /dev/null; then
      echo "gentoolkit already installed"
    else
      emerge -q app-portage/gentoolkit > /dev/null
    fi

- name: "Install postgres"
  become: "yes"
  portage:
    package:
      - "dev-db/postgresql"
      - "dev-python/psycopg"

- name: "Verify data dir"
  become: yes
  register: postgres_data_dir
  file:
    path: /var/lib/postgresql/13/data
    ensure: file

- name: verify variable
  debug:
    var: postgres_data_dir

- name: "Configure postgres with emerge"
  become: "yes"
  shell: "emerge --config dev-db/postgresql"
  when:

- name: "Start postgresql service"
  become: "yes"
  register: start_service
  service:
    name: "postgresql-13"
    enabled: "yes"
    state: "started"

- name: show service
  debug:
    var: start_service

- name: "Create postgres database"
  become: "yes"
  become_user: "postgres"
  community.postgresql.postgresql_db:
    name: "postgres"
    owner: "postgres"

- name: "Create postgres schema"
  become: "yes"
  become_user: "postgres"
  community.postgresql.postgresql_schema:
    name: "app"
    owner: "postgres"
