---
name: Molecule Test
on: [push, pull_request]
jobs:
  test-modules:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        module: ["combined", "nginx", "postgres"]
    steps:
      - uses: actions/checkout@v2
      - name: Test modules
        if: contains("combined", matrix.module)
        run: |
          cd ${{ matrix.module }}
          mol test
      - name: Test modules
        if: !contains("combined", matrix.module)
        run: |
          mol test
